; rabin_zx.asm — on-device Rabin-Williams-1024 verify demo for ZX Spectrum / Fuse.
; Runs the full verify (SHA-256 + s^2 mod n + untweak + redundancy check) on each
; embedded vector and prints OK/BAD, times one full verify with the 50 Hz FRAMES
; counter, then a tamper test (flip one artifact byte -> must read BAD) and the
; artifact digest.  Verify pipeline lives in rabin_core.inc.asm; vectors are
; generated by rabin_sign.js.
; Build: sjasmplus rabin_zx.asm  ->  rabin_zx.tap
;
; Interrupts stay ENABLED: bn_core.inc.asm and sha_core.inc.asm are IY-free, so
; IY stays $5C3A (what the ROM ISR + RST $10 need) the whole time — no DI needed,
; and FRAMES keeps counting so the tap can self-time.

FRAMES  equ 23672
vidx    equ $B300          ; display index 0..NVEC-1
vrem    equ $B301          ; remaining vectors
vptr    equ $B302          ; pointer into rv_vectors
deltaf  equ $B304          ; elapsed frames
lz      equ $B306          ; pdec16 leading-zero flag

    DEVICE ZXSPECTRUM48
        org $8000
main:
        ld a,2
        call $1601                 ; open the upper screen as channel 2
        ld de,s_title
        call pstr

        ; artifact is the same for every vector -> load it once
        ld hl,rv_artifact
        ld de,msgbuf
        ld bc,RV_ARTLEN
        ldir
        ld a,RV_ARTLEN
        ld (msglen),a

        ; --- verify every embedded vector ---
        ld hl,rv_vectors
        ld (vptr),hl
        xor a
        ld (vidx),a
        ld a,RV_NVEC
        ld (vrem),a
vloop:
        call load_vector           ; n,s,tw_e,tw_f from (vptr); advance vptr
        call rabin_verify          ; verdict -> (result)
        call print_result          ; "vN eE f± OK/BAD"
        ld a,(vidx)
        inc a
        ld (vidx),a
        ld a,(vrem)
        dec a
        ld (vrem),a
        jr nz,vloop

        ; --- time one full verify (vector 0) ---
        ld de,s_tim
        call pstr
        ld hl,rv_vectors
        ld (vptr),hl
        call load_vector
        ld hl,(FRAMES)
        push hl
        call rabin_verify
        ld hl,(FRAMES)
        pop de
        or a
        sbc hl,de
        ld (deltaf),hl
        call pdec16                ; frames
        ld de,s_frames
        call pstr
        ld hl,(deltaf)             ; whole seconds = frames / 50
        call div50
        ld l,c : ld h,b
        call pdec16
        ld a,'.'
        rst $10
        ld hl,(deltaf)             ; tenths = (frames mod 50) / 5
        call div50
        ld de,5
        ld a,'0'
t_lp:
        or a
        sbc hl,de
        jr c,t_done
        inc a
        jr t_lp
t_done:
        rst $10
        ld a,'s'
        rst $10
        call pcrlf

        ; --- tamper test: flip one artifact byte -> verify must read BAD ---
        ld de,s_tamp
        call pstr
        ld hl,rv_vectors
        ld (vptr),hl
        call load_vector
        ld a,(msgbuf)
        xor 1
        ld (msgbuf),a              ; corrupt
        call rabin_verify
        ld a,(msgbuf)
        xor 1
        ld (msgbuf),a             ; restore
        call print_verdict
        call pcrlf

        ; --- show the artifact digest (end result) ---
        ld de,s_dg
        call pstr
        call print_digest
        ret

; load_vector: copy n,s,tw_e,tw_f from (vptr); advance vptr to the next record
load_vector:
        ld hl,(vptr)
        ld de,n
        ld bc,128
        ldir                       ; n  (HL -> s field)
        ld de,s
        ld bc,128
        ldir                       ; s  (HL -> e field)
        ld a,(hl) : ld (tw_e),a : inc hl
        ld a,(hl) : ld (tw_f),a : inc hl
        ld (vptr),hl
        ret

; print_result: "vN eE f± " then verdict + newline
print_result:
        ld a,'v' : rst $10
        ld a,(vidx) : add a,'0' : rst $10
        ld a,' ' : rst $10
        ld a,'e' : rst $10
        ld a,(tw_e) : add a,'0' : rst $10
        ld a,' ' : rst $10
        ld a,'f' : rst $10
        ld a,(tw_f) : cp 1 : jr z,pr_plus
        ld a,'-' : jr pr_sgn
pr_plus:
        ld a,'+'
pr_sgn:
        rst $10
        ld a,' ' : rst $10
        call print_verdict
        jp pcrlf

; print_verdict: "OK" if (result)!=0 else "BAD"
print_verdict:
        ld a,(result)
        or a
        jr z,pv_bad
        ld de,s_ok
        jp pstr
pv_bad:
        ld de,s_bad
        jp pstr

print_digest:                      ; print 32 bytes at `digest` as hex + newline
        ld hl,digest
        ld b,32
pd_lp:
        ld a,(hl)
        call phex8
        inc hl
        djnz pd_lp
        jp pcrlf

; ---- print helpers (shared style with sha_zx.asm) ----
pstr:
        ld a,(de)
        or a
        ret z
        rst $10
        inc de
        jr pstr
pcrlf:
        ld a,13
        rst $10
        ret
phex8:
        push af
        rra : rra : rra : rra
        call phnib
        pop af
phnib:
        and $0f
        add a,$90
        daa
        adc a,$40
        daa
        rst $10
        ret
pdec16:                            ; print HL unsigned decimal, no leading zeros
        ld a,1
        ld (lz),a
        ld de,10000 : call pdig
        ld de,1000  : call pdig
        ld de,100   : call pdig
        ld de,10    : call pdig
        ld a,l
        add a,'0'
        rst $10
        ret
pdig:
        ld c,'0'
pd_l:
        or a
        sbc hl,de
        jr c,pd_d
        inc c
        jr pd_l
pd_d:
        add hl,de
        ld a,c
        cp '0'
        jr nz,pd_emit
        ld a,(lz)
        or a
        ret nz
        ld a,'0'
        rst $10
        ret
pd_emit:
        xor a
        ld (lz),a
        ld a,c
        rst $10
        ret
div50:                             ; HL/50 -> BC=quotient, HL=remainder
        ld bc,0
dv_l:
        or a
        ld de,50
        sbc hl,de
        jr c,dv_d
        inc bc
        jr dv_l
dv_d:
        add hl,de
        ret

s_title:  db "ZXPkg Rabin-1024 verify", 13, 13, 0
s_tim:    db "time: ", 0
s_frames: db " fr = ", 0
s_tamp:   db "tamper(want BAD): ", 0
s_dg:     db "dg: ", 0
s_ok:     db "OK", 0
s_bad:    db "BAD", 0

        INCLUDE "rabin_core.inc.asm"
        INCLUDE "bn_core.inc.asm"
        INCLUDE "sha_core.inc.asm"
        INCLUDE "vectors/rabin_vectors.inc.asm"
code_end:

; ---- BASIC autoloader: CLEAR VAL "32767": LOAD ""CODE: RANDOMIZE USR VAL "32768"
basic_prog:
        db 0, 10
        dw basic_lend - basic_lbody
basic_lbody:
        db $FD, $B0, $22, "32767", $22, $3A
        db $EF, $22, $22, $AF, $3A
        db $F9, $C0, $B0, $22, "32768", $22
        db $0D
basic_lend:
basic_end:

        EMPTYTAP "rabin_zx.tap"
        SAVETAP  "rabin_zx.tap", BASIC, "rabin", basic_prog, basic_end - basic_prog, 10
        SAVETAP  "rabin_zx.tap", CODE,  "rabin", main, code_end - main, $8000
